### PR TITLE
Added support UTF-8

### PR DESCRIPTION
**Pull request by kickdev**

### CODE REVIEW

**Comment by ivantcholakov** [comment]
@kickdev

You should have checked whether mbstring extension is loaded.

**Comment by ivantcholakov** [comment]
```php
static $mbstring_installed = null;

if ($mbstring_installed === null) {
    $mbstring_installed = extension_loaded('mbstring');
}

if ($mbstring_installed) {
    $this->name_initials .= mb_strtoupper(trim(mb_substr($word, 0, 1, 'UTF-8')));
} else {
    $this->name_initials .= strtoupper(trim($word[0]));
}
```

**Comment by ivantcholakov** [comment]
Or better:

```php
static $mbstring_installed = null;

if ($mbstring_installed === null) {
    $mbstring_installed = function_exists('mb_strlen');
}

if ($mbstring_installed) {
    $this->name_initials .= mb_strtoupper(trim(mb_substr($word, 0, 1, 'UTF-8')));
} else {
    $this->name_initials .= strtoupper(trim($word[0]));
}
```

**Comment by kickdev** [comment]
What for? If you think about these crutches, and any hosting or WAMP, LAMP, MAMP provides an extension. In addition, we use a composer. Add to block requirement "ext-mbstring" : "*"

**Comment by ivantcholakov** [comment]
@kickdev By your assumption you introduce gambling in this package. I know that mbstring would be installed in most servers, but probability is not 100%. It is not.

The block requirement: I use Composer on a development machine, not on the real server. I deploy my software just by uploading everything, so the second suggestion of yours is not a solution for me.

**Comment by kickdev** [comment]
Well, I'll revise this piece of code and do it differently with UTF-8 support, since UTF-8 support is very important for many users.

**Comment by ivantcholakov** [comment]
I did some modifications in my place. Basically it is defining internal methods strtoupper() and substring(). https://github.com/ivantcholakov/starter-public-edition-4/commit/4275b756cf0660232dbeaa7b57f9bdad47658a25

You could do something similar by checking against mbstring and iconv and using these extensions if they are available.

**Pull request merged**
